name: Build EZFT

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      INCLUDE: '${{env.WATCOM}}/h'

    steps:
      - uses: actions/checkout@v2
      - uses: open-watcom/setup-watcom@v0
        with:
          version: "2.0"
      - run: |
          echo $INCLUDE
          wmake
