name: Build EZFT

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: open-watcom/setup-watcom@v0
        with:
          version: "2.0"
      - run: |
          wcl -i"${{env.WATCOM}}/h" -0 -ml -wx -bt=dos *.c
