name: Build EZFT

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: open-watcom/setup-watcom@v0
        with:
          version: "2.0"
      - run: |
          pwd
      - run: |
          wmake
